import streamlit as st
import streamlit.components.v1 as components

# 1. 網頁頁面初始化設定（強制全螢幕、純黑背景）
st.set_page_config(page_title="究極黑客控制台 v11.6", page_icon="💀", layout="wide")

# 強制隱藏 Streamlit 的所有原生網頁 UI
st.markdown(
    """
    <style>
    [data-testid="stHeader"], footer, #MainMenu {visibility: hidden !important;}
    .stApp {background-color: #000000 !important;}
    .block-container {padding: 0px !important; max-width: 100% !important; margin: 0px !important;}
    
    /* 強制讓元件的內外層容器都具備完整的滾動能力 */
    [data-testid="stHtmlBlock"], [data-testid="stElementContainer"], iframe {
        width: 100% !important;
        height: 100vh !important;
        display: block !important;
        border: none !important;
    }
    body {
        overflow: hidden !important;
    }
    </style>
    """, 
    unsafe_allow_html=True
)

# 2. 透過安全陣列相加機制，部署超級加長版的黑客日誌引擎
html_parts = [
    '<!DOCTYPE html>',
    '<html lang="zh-TW">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <title>Matrix Terminal Ultimate</title>',
    '    <style>',
    '        * { box-sizing: border-box; }',
    '        body, html {',
    '            margin: 0;',
    '            padding: 0;',
    '            background-color: #000;',
    '            overflow: hidden;',
    '            width: 100%;',
    '            height: 100vh;',
    '            font-family: "Courier New", Courier, monospace;',
    '        }',
    '        canvas {',
    '            display: block;',
    '            position: absolute;',
    '            top: 0;',
    '            left: 0;',
    '            z-index: 1;',
    '            opacity: 0.15;',
    '        }',
    '        #terminal {',
    '            position: absolute;',
    '            top: 0;',
    '            left: 0;',
    '            width: 100%;',
    '            height: 100vh;',
    '            z-index: 2;',
    '            padding: 40px;',
    '            color: #00ff00;',
    '            font-size: 18px;',
    '            line-height: 1.6;',
    '            overflow-y: auto;',
    '            white-space: pre-wrap;',
    '            word-wrap: break-word;',
    '            text-shadow: 0 0 4px #00ff00;',
    '        }',
    '        #terminal::-webkit-scrollbar {',
    '            display: none;',
    '        }',
    '        .cursor {',
    '            display: inline-block;',
    '            background-color: #00ff00;',
    '            width: 10px;',
    '            height: 18px;',
    '            animation: blink 0.8s infinite;',
    '            vertical-align: middle;',
    '        }',
    '        @keyframes blink {',
    '            0%, 49% { background-color: #00ff00; }',
    '            50%, 100% { background-color: transparent; }',
    '        }',
    '        #success-overlay {',
    '            display: none;',
    '            position: fixed;',
    '            top: 50%;',
    '            left: 50%;',
    '            transform: translate(-50%, -50%);',
    '            z-index: 999;',
    '            background-color: rgba(0, 0, 0, 0.95);',
    '            border: 3px solid #00ff00;',
    '            padding: 40px;',
    '            text-align: center;',
    '            color: #00ff00;',
    '            font-size: 28px;',
    '            font-weight: bold;',
    '            box-shadow: 0 0 30px #00ff00;',
    '            letter-spacing: 2px;',
    '        }',
    '        #hidden-input {',
    '            position: absolute;',
    '            opacity: 0;',
    '            z-index: -1;',
    '        }',
    '        .log-line {',
    '            margin-bottom: 4px;',
    '        }',
    '    </style>',
    '</head>',
    '<body>',
    '    <canvas id="canvas"></canvas>',
    '    <div id="terminal">',
    '        <div class="log-line">=================================================================================</div>',
    '        <div class="log-line">💀 首席網路安全專家：[REDACTED] | 核心控制終端戰略部署面板 v11.6</div>',
    '        <div class="log-line">=================================================================================</div>',
    '        <div class="log-line">&gt;&gt; CORE STATUS: ONLINE // SYSTEM INTEGRITY: SECURE</div>',
    '        <div class="log-line">&gt;&gt; INFILTRATION PROTOCOL: ACTIVE [ANONYMOUS NODE]</div>',
    '        <div class="log-line">&gt;&gt; SUBSYSTEMS LOADED: QUANTUM CRYPTO / SHADOW PROXY v2.4</div>',
    '        <div class="log-line"></div>',
    '        <div id="dynamic-content"></div>',
    '        <div id="input-line">root@ghost-terminal:~# <span class="cursor"></span></div>',
    '    </div>',
    '    <input type="text" id="hidden-input" autofocus>',
    '    <div id="success-overlay">',
    '        💀 [SYSTEM UNLOCKED] 你已成功侵入 💀<br>',
    '        ================================================<br>',
    '        ACCESS GRANTED // 核心控制權限獲取成功！<br>',
    '        指揮官：ANONYMOUS OPERATOR 已全面接管目標主機。',
    '    </div>',
    '    <script>',
    '        const canvas = document.getElementById("canvas");',
    '        const ctx = canvas.getContext("2d");',
    '        function resizeCanvas() {',
    '            canvas.width = window.innerWidth;',
    '            canvas.height = window.innerHeight;',
    '        }',
    '        resizeCanvas();',
    '        window.addEventListener("resize", resizeCanvas);',
    '        const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789🧬💀🛰️🔥🔓🚀💥⚡";',
    '        const alphabet = chars.split("");',
    '        const fontSize = 16;',
    '        let columns = canvas.width / fontSize;',
    '        const rainDrops = Array(Math.floor(columns)).fill(1);',
    '        function drawMatrix() {',
    '            ctx.fillStyle = "rgba(0, 0, 0, 0.05)";',
    '            ctx.fillRect(0, 0, canvas.width, canvas.height);',
    '            ctx.fillStyle = "#0F0";',
    '            ctx.font = fontSize + "px monospace";',
    '            for (let i = 0; i < rainDrops.length; i++) {',
    '                const text = alphabet[Math.floor(Math.random() * alphabet.length)];',
    '                ctx.fillText(text, i * fontSize, rainDrops[i] * fontSize);',
    '                if (rainDrops[i] * fontSize > canvas.height && Math.random() > 0.975) {',
    '                    rainDrops[i] = 0;',
    '                }',
    '                rainDrops[i]++;',
    '            }',
    '        }',
    '        setInterval(drawMatrix, 30);',
    '        const terminal = document.getElementById("terminal");',
    '        const dynamicContent = document.getElementById("dynamic-content");',
    '        const inputLine = document.getElementById("input-line");',
    '        const hiddenInput = document.getElementById("hidden-input");',
    '        const successOverlay = document.getElementById("success-overlay");',
    
    # 擴充後的超豐富標籤、動作、與目標庫
    '        const tags = ["INFO", "WARN", "SYSTEM", "INJECT", "DECRYPT", "BYPASS", "CONNECT", "EXPLOIT", "STDOUT", "KERNEL", "TRACE", "NETWORK", "SECURITY", "OVERFLOW"];',
    '        const actions = [',
    '            "正在偵測通訊埠漏洞", "成功繞過防火牆安全認證層", "攔截核心加密資料庫封包", ',
    '            "正在注入隱形後門 Trojan.Core", "啟動量子演算法破解私鑰", "成功切換虛擬本地代理網段", ',
    '            "遠端溢位攻擊成功", "正在強制同步資料傳輸緩衝區", "核心偽裝層部署完畢", "全面癱瘓伺服器流量",',
    '            "正在進行堆疊溢位漏洞探測 (Stack Smashing Check)", "劫持核心控制流程指標 (RIP Pointer Hijacking)",',
    '            "正在執行多重路由跳躍偽裝 (Onion Routing Encapsulation)", "成功提取記憶體分頁表結構 (Paging Table Dump)",',
    '            "發射阻斷服務同步攻擊流 (SYN-Flood Stream Broadcaster)", "破譯 SSL/TLS 安全交握憑證鏈",',
    '            "注入無權限惡意符號鏈結 (Symbolic Link Invalidation)", "繞過核心地址空間隨機化 (ASLR Bypass Matrix)",',
    '            "執行沙盒環境溢位逃逸處理 (Sandbox Escape Exploit)", "重組已被中斷的核心 TCP 分段封包"',
    '        ];',
    '        const targets = [',
    '            "nasa.gov.secure", "pentagon.admin.node", "mainframe.central.bank", "global.dns.server", ',
    '            "crypto.vault.ledger", "security.gateway.firewall", "backbone.root.switch", "cloud.matrix.core",',
    '            "root@nsa.internal.gateway", "mainframe.telecom.switchboard", "satellite.orbit.control.node",',
    '            "darknet.relay.onion-09", "core.kernel.ring0-scheduler", "isolated.vault.airgapped.subnet"',
    '        ];',
    '        const scripts_pool = [',
    '            "for (int i = 0; i < 1024; i++) { malloc(sizeof(payload)); }", ',
    '            "connect_to_proxy_node(\'SOCKS5://103.24.51.9\', port=22);", ',
    '            "if (auth_token == \'BYPASS_TRUE\') { grant_root_access(); }", ',
    '            "AES_256_Decrypt(key_matrix, cipher_text, chunk_size=4096);", ',
    '            "iptables -A INPUT -s 127
